# Generated by Django 2.0.9 on 2018-11-17 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworkimage',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='frameworks.Framework'),
        ),
    ]
