# Generated by Django 2.0.9 on 2018-11-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('frameworks', '0002_auto_20181117_0315'),
        ('tutorials', '0004_auto_20181114_0404'),
        ('zinnia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='news', to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='entry',
            name='frameworks',
            field=models.ManyToManyField(blank=True, related_name='news', to='frameworks.Framework'),
        ),
        migrations.AddField(
            model_name='entry',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='news', to='tutorials.Series'),
        ),
    ]
