# Generated by Django 2.0.9 on 2018-11-11 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import image_cropping.fields
import markdownx.models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frameworks', '0001_initial'),
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagulous_Tutorial_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
                ('path', models.TextField()),
                ('label', models.CharField(help_text='The name of the tag, without ancestors', max_length=255)),
                ('level', models.IntegerField(default=1, help_text='The level of the tag in the tree')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tutorials.Tagulous_Tutorial_tags')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagTreeModel, models.Model),
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('content', markdownx.models.MarkdownxField(blank=True)),
                ('url', models.URLField(blank=True, max_length=300, null=True)),
                ('credit_note', models.CharField(blank=True, max_length=255)),
                ('image', image_cropping.fields.ImageCropField(blank=True, upload_to='uploaded_images')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('assets', models.ManyToManyField(blank=True, related_name='tutorials', to='assets.Asset')),
                ('frameworks', models.ManyToManyField(blank=True, related_name='tutorials', to='frameworks.Framework')),
                ('languages', models.ManyToManyField(blank=True, related_name='tutorials', to='languages.Language')),
                ('tags', tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', space_delimiter=False, to='tutorials.Tagulous_Tutorial_tags', tree=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users_liked', models.ManyToManyField(blank=True, related_name='tutorials_liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'tutorials',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='TutorialImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', image_cropping.fields.ImageCropField(blank=True, upload_to='uploaded_images')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frameworks.Framework')),
            ],
            options={
                'ordering': ['order', 'date_add'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_tutorial_tags',
            unique_together={('slug', 'parent')},
        ),
    ]
