# Generated by Django 2.0.9 on 2018-11-13 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-updated'], 'verbose_name_plural': 'tutorials'},
        ),
        migrations.AddField(
            model_name='tutorialmembership',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Series'),
        ),
        migrations.AddField(
            model_name='tutorialmembership',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Tutorial'),
        ),
        migrations.AddField(
            model_name='series',
            name='tutorials',
            field=models.ManyToManyField(through='tutorials.TutorialMembership', to='tutorials.Tutorial'),
        ),
    ]
