# Generated by Django 2.0.9 on 2018-11-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20181114_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
